### ISSUE TITLE
The exception list for instances we don't want to delete

### ISSUE THREAD

**Issue by jyejare** [RedHatQE/cloudwash#11]
Requester: Sharon Brown

Issue: Would like to have an exception list for instances we don't want to delete. but currently, we have an exception list to stop the instance but not completely to escape it.

Urgency: Not mentioned but looks like a promising future. 

Willing to Contribute: Not mentioned!

**Comment by lukas-bednar** [comment]
We also need such functionality

**Comment by jyejare** [comment]
The PR is merged in master and expect the release soon ! @lukas-bednar !
