### ISSUE TITLE
Update README with table showing supported types and cloud providers

### ISSUE THREAD

**Issue by jyejare** [RedHatQE/cloudwash#117]

**Comment by anchalsingh2929** [comment]
Hi, @jyejare  this seems like a good first issue , I would like to work on this issue , can you assign this to me.
I had a discussion with @lyfofvipin on the same.

**Comment by lyfofvipin** [comment]
Hi @anchalsingh2929  Here are the required data for the table.
```
AWS
  --nics    Remove only unused NICs from the provider
  --discs   Remove only unused DISCs from the provider
  --vms     Remove only unused VMs from the provider
  --images  Remove only images from the provider
  --pips    Remove only Public IPs from the provider
  --stacks  Remove only CloudFormations from the provider

Azure
  --nics    Remove only unused NICs from the provider
  --discs   Remove only unused DISCs from the provider
  --vms     Remove only unused VMs from the provider
  --images  Remove only images from the provider
  --pips    Remove only PiPs from the provider

GCE
  --nics   Remove only unused NICs from the provider
  --discs  Remove only unused DISCs from the provider
  --vms    Remove only unused VMs from the provider

OpenStack
  --nics   Remove only unused NICs from the provider
  --discs  Remove only unused DISCs from the provider
  --vms    Remove only unused VMs from the provider

VMware
  --nics   Remove only unused NICs from the provider
  --discs  Remove only unused DISCs from the provider
  --vms    Remove only unused VMs from the provider

RHEV
  --nics   Remove only unused NICs from the provider
  --discs  Remove only unused DISCs from the provider
  --vms    Remove only unused VMs from the provider
```

**Comment by jyejare** [comment]
@anchalsingh2929 Assigned this to you ! Welcome to contribute in cloudwash !! 

@lyfofvipin Lets not add any details about Openstack, VMWare and RHEV for now , those are not yet implemented :)

**Comment by jyejare** [comment]
@anchalsingh2929 There is an also option called `--all` in all providers cleanup that would clean all the resource type resoueces , good mnetion that in docs!

**Comment by anchalsingh2929** [comment]
Thanks @lyfofvipin and @jyejare  for the information , will be submitting pull request for the same soon.

**Comment by lyfofvipin** [comment]
Hi @jyejare `--all` flag is already in the docs and I also can't find a place to put the same in the table so skipped the same any suggestion on the same is welcome.

**Comment by jyejare** [comment]
@lyfofvipin Sure! Not in the table but just mention that its not always that one need not to mention individual type options but can also use `--all` to clean all resource types. A single line should be good enough !

**Comment by lyfofvipin** [comment]
Sure sounds good to me.

**Comment by anchalsingh2929** [comment]
Hi @jyejare added a Note in the PR for --all flag.
