### ISSUE TITLE
How to delete resources from all regions in AWS?

### ISSUE THREAD

**Issue by kornys** [RedHatQE/cloudwash#12]
From configuration and brief check of source I don't see any chance how to clean resources across all regions in AWS. Also configuration allows only define one region for ec2 and the most weird part is username and password for ec2... AWS allows you to use api account with id and key so this tool should be able to reuse it.

**Comment by eduardocerqueira** [comment]
it is a good question @kornys, I was checking the code and I agree with you, it seems cloudwash is tied with only one AWS region at least on this code version. @jyejare is there any plan to extend the tool to manage resources from multiple regions?

**Comment by kornys** [comment]
boto3 client allows you after connecting into specific region list all regions so then you can iterate across regions and connect ec2 client to specific region and list instances. I expect that same approach can be used for other aws objects.

**Comment by jyejare** [comment]
@eduardocerqueira @kornys Since we have this issue open now, we will try to fix it up sooner depends on multiple priorities listed in the issues.

@kornys I would encourage you to step forward and contribute to a fix the issue.

**Comment by jyejare** [comment]
@kornys @eduardocerqueira The recent PR #19 has merged adding support for multiple regions where you can either mention one region, multiple separated by comma or `all` string. The `all` fetches list of regions from EC2 and runs cleanup over all regions.

Also the username and password itself are nothing but `aws_access_key_id` and `aws_secret_access_key` resp, it is just that cloudwash is using the term username and passwrd from its dependency wrapanapi https://github.com/RedHatQE/wrapanapi/blob/master/wrapanapi/systems/ec2.py#L492-L493

If thats confusing things then we ll change that in the future.
