### ISSUE TITLE
Incorrect log messages

### ISSUE THREAD

**Issue by psrna** [RedHatQE/cloudwash#30]
Hello,

I've run the tool to clean up EC2 instances. It run successfully, however the tool mentioned "azure" instead of "aws" in the log message.

<<<<<<< Running the cleanup script in ACTION mode >>>>>>> 
The EC2 providers settings are initialized and validated !
Stopped [] and removed ['testcloudwash-xkmdw-master-1', 'testcloudwash-xkmdw-master-2', 'testcloudwash-xkmdw-master-0', 'testcloudwash-xkmdw-worker-us-east-1a-jf4l2', 'testcloudwash-xkmdw-worker-us-east-1a-ff7gn'] VMs from Azure Cloud.
Removed following and all unused nics from Azure Cloud. 
['eni-078c16e35914e3189', 'eni-004e575b611e2e356', 'eni-06c75dd20d94f45fa']
Removed following and all unused discs from Azure Cloud. 
[]
Removed following and all unused pips from Azure Cloud. 
[]

**Comment by psrna** [comment]
@jyejare I'm using quay.io/dno/jenkins_cloudwash image. Not sure what version was there. Maybe worth checking if the image gets republished with each release.

**Comment by jyejare** [comment]
@psrna No thats not updated afaik. Harel had plans to update the document to use image quay.io/redhatqe/cloudwash which is auto updated on release.

**Comment by hareldev** [comment]
Hello @psrna, if you're using the reference Jenkinsfile, please note it was updated few weeks ago with the following variable in `Line 2`:
```
SWACH_IMAGE = "quay.io/redhatqe/cloudwash:latest"
```
Make sure you're using this version, so you'll get the updated version.

**Comment by jyejare** [comment]
Closing this now as we have fixed it in recent builds !
